package ai.utkarsh.db_admin_assisstant.domain.audit.model;

public enum AuditAction {
    DATABASE_REGISTERED,
    DATABASE_ENABLED,
    DATABASE_DISABLED,
    RECOMMENDATION_CREATED,
    RECOMMENDATION_APPROVED,
    RECOMMENDATION_REJECTED,
    RECOMMENDATION_APPLIED,
    RECOMMENDATION_APPLY_FAILED,
    ADMIN_LOGIN
}
