package ai.utkarsh.db_admin_assisstant.domain.audit.model;

public enum AuditAction {
    DATABASE_REGISTERED,
    DATABASE_ENABLED,
    DATABASE_DISABLED,
    DATABASE_DELETED,
    RECOMMENDATION_CREATED,
    RECOMMENDATION_APPROVED,
    RECOMMENDATION_REJECTED,
    RECOMMENDATION_APPLIED,
    RECOMMENDATION_ALREADY_EXISTS,
    RECOMMENDATION_APPLY_FAILED,
    ADMIN_LOGIN,
    ADMIN_USER_CREATED,
    ADMIN_USER_ROLE_CHANGED,
    ADMIN_USER_ENABLED,
    ADMIN_USER_DISABLED,
    QUERY_EXECUTED,
    SCHEMA_VIEWED,
    AI_SQL_QUERY_ASKED,
    SENSITIVE_COLUMN_MARKED,
    SENSITIVE_COLUMN_UNMARKED
}
